Clean: Reformatted 'run-clang-format.py'.

diff --git a/.github/workflows/build-goom-lib-only.yml b/.github/workflows/build-goom-lib-only.yml
--- a/.github/workflows/build-goom-lib-only.yml
+++ b/.github/workflows/build-goom-lib-only.yml
@@ -140,13 +140,14 @@ jobs:
           cd ${{ env.VIS_GOOM_PATH }}
           echo "PWD = \"${PWD}\"."
 
-          python3 scripts/run-clang-format.py --clang-format-executable "clang-format-${{ vars.CLANG_FORMAT_VER }}" \
-                                              -i -r \
-                                              -e "*particles/src/glm" \
-                                              -e "*docker-toolchains/unicode.h" \
-                                              -e "*lsys/src/*.c" -e "*lsys/src/lexdefs.h" -e "*lsys/src/lsys.tab.h" \
-                                              -e "*build-*" -e "*vivid*" -e "*bezier" -e "*perlin_noise*" -e "*magic_enum*" \
+          python3 scripts/run-clang-format.py --clang-format-exe "clang-format-${{ vars.CLANG_FORMAT_VER }}" \
+                                              --recursive \
                                               "${PWD}"
+          if [[ $? != 0 ]]; then
+            echo "ERROR: clang-format failure."
+            echo
+            exit 1
+          fi
           if [[ "$(git diff --name-only)" != "" ]]; then
             echo "ERROR: clang-format problem."
             echo
@@ -188,7 +189,7 @@ jobs:
         run: |
           cd ${{ env.VIS_GOOM_PATH }}/${{ env.GOOM_LIBS_DIR }}
           echo "PWD = \"${PWD}\"."
-          
+
           run-clang-tidy-${{ vars.CLANG_VER}} -j $(getconf _NPROCESSORS_ONLN) \
                                               -header-filter='^((?!catch2).)*$' \
                                               -p ${{ env.BUILD_PATH }} \
